aws-samples/remote-swe-agents

AmazonQ.md, slack-bolt-app/src/app.ts, worker/src/agent/common/messages.ts
This PR implements the feature requested in issue #12 to allow agents programmatic access to images by:
1. Saving incoming images to the local filesystem at `~/.remote_swe_workspace/images/image[seqNo].[extension]`
2. Appending a text block after each image block with path information
3. Maintaining a sequence counter that increments for each image and resets when the process is killed
- Added utility functions to save images locally
- Modified `postProcessMessageContent` to append text blocks with path info
- Images are saved as webp format (matching the existing conversion)
Fixes #12
=> Save images locally and provide path info in messages

worker/src/agent/common/messages.ts
This PR fixes issue #16 by changing the image format from webp to JPEG when saving images locally.
- Modified the `saveImageToLocalFs` function to convert webp images to JPEG format before saving
- WebP format is still used in the `postProcessMessageContent` function for efficiency
- Changed file extension from 'webp' to 'jpeg'
This change improves compatibility with various CLI tools that may not handle webp files as easily as JPEG.
closes #16
=> Save images in JPEG format locally for better CLI compatibility

worker/src/agent/index.ts
This PR addresses issue #24.
- Modified the prompt to have agents explicitly request user response at the end of their turns
- Added a new instruction in the Communication Style section that directs the agent to clearly indicate when it's waiting for user input
- The prompt is language-agnostic and allows flexible formats for requesting responses
Fixes #24
=> Prompt agent to explicitly request user response at turn end

README.md
This PR addresses issue #27 with the following improvements to the README.md:
1. Added clarification that Bedrock Claude Sonnet 3.7 model needs to be enabled in both us-east-1 and us-west-2 regions
2. Added 'proceed to next step' instructions at the end of each numbered step to improve user flow
3. Added guidance on when to use Personal Access Token vs GitHub App for GitHub integration
4. Enhanced overall readability with clearer instructions throughout the setup process
Fixes #27
=> Improve README.md with clearer instructions

worker/src/agent/index.ts
This PR adds instructions to the system prompt that encourage agents to create execution plans before implementing changes.
The prompt now instructs agents to:
1. Create an execution plan first for complex tasks
2. Present the plan to the user for review
3. Include key details like requirements understanding, implementation approach, files to modify, and risks
4. Only start implementation after explicit confirmation
This addresses issue #29: Agent should create a plan first before actually implementing it.
Fixes #29
=> Add planning workflow to system prompt

worker/src/agent/index.ts
closes #34 
root cause: cacheWriteInputTokens was ignored when calculating input token count.
=> fix token count issue

slack-bolt-app/src/app.ts, slack-bolt-app/src/util/history.ts, worker/src/agent/common/bedrock.ts, worker/src/agent/common/messages.ts, worker/src/agent/index.ts, worker/src/agent/tools/report-progress/index.ts, worker/src/agent/tools/think/index.ts
This PR tries to resolve the problem that an agent does not send any message for a while after user's message, making users confused if the agent is stuck or not.
To improve the situation, we use [toolConfig](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ToolConfiguration.html#bedrock-Type-runtime_ToolConfiguration-tools) to force the agent to use reportProgress tool. To let the agent decide not to use the tool, we also added a think tool (kind of no-op tool in this case, but it will also improve the agents' thought capability), and toolConfig any option.
Because toolConfig option cannot be enabled with reasoning option, we need special handling for the props.
By submitting this pull request, I confirm that you can …
=> use reportProgress tool in a more robust way

cdk/test/__snapshots__/cdk.test.ts.snap, packages/agent-core/src/lib/index.ts, packages/agent-core/tsconfig.json, packages/slack-bolt-app/src/util/history.ts, packages/worker/src/agent/index.ts, packages/worker/src/local.ts
This PR makes boltApp send the below prompt right after a user message, making an initial response faster and UX better.
https://github.com/aws-samples/remote-swe-agents/blob/cfccb7754740cc8a1cfad9d86aa0211ef817e83a/packages/agent-core/src/lib/prompt.ts#L14-L22
=> send quick response after the user message

cdk/lib/constructs/worker/index.ts, cdk/test/__snapshots__/cdk.test.ts.snap
This PR implements caching for source.tar.gz file based on S3 ETag values to improve myapp service startup performance.
- Added logic to check S3 ETag before downloading source.tar.gz
- Implemented caching mechanism to store extracted files locally
- Added conditional logic to use cached files when ETag hasn't changed
- Added ETag storage at /opt/myapp/.source_etag to track file changes
The implementation follows these steps:
1. When myapp starts, check if a cached ETag exists
2. If it exists, compare with current S3 ETag using head-object API call
3. If ETags match, use the cached extracted files instead of downloading again
4. If ETags differ or no cache exists, download the file and update the cache
This change should significantly improve startup time when source.tar.gz hasn't …
=> Cache source.tar.gz using S3 ETag

README_ja.md
This PR adds README_ja.md as a Japanese translation of the original README.md.
- Created a new file README_ja.md with translated content from README.md
- Covered all sections including installation instructions
- Maintained the original structure and formatting
This will help Japanese-speaking users better understand how to use and set up remote-swe-agents.
=> Add README_ja.md: Japanese version of README

README.md
This PR adds a link to the Japanese version of the README (README_ja.md) in the original README.md file.
- Added a link to the Japanese README in the introduction section (just before the concept image)
- Implemented the link with the text: \"*日本語版のREADMEは[こちら](README_ja.md)をご覧ください。*\" (Japanese README is available [here])
This makes it easier for Japanese-speaking users to find the Japanese version of the README.
=> Add link to Japanese README in the main README

package-lock.json, packages/slack-bolt-app/package.json, packages/slack-bolt-app/src/app.ts, packages/slack-bolt-app/src/async-handler.ts, packages/slack-bolt-app/src/util/worker-manager.ts
Currently, if we got any error in worker manager, it fails silently. To let user (or developer) know what's happening more precisely, this PR will make it send error detail to slack.
=> notify error in worker manager

AmazonQ.md, cdk/lib/constructs/storage.ts, cdk/lib/constructs/worker/image-builder.ts, cdk/test/__snapshots__/cdk.test.ts.snap, packages/slack-bolt-app/src/app.ts, packages/slack-bolt-app/src/util/history.ts
Implements issue #74: Allow to list all the previous sessions with DynamoDB query
BREAKING CHANGE: This PR replaces the DynamoDB table schema. We accept this since currently there should not be many users for this.
When creating a new session (i.e. new Slack thread), we store the following item in the DynamoDB table:
- PK: sessions
- SK: workerId
- workerId
- createdAt
- LSI1: Date.now().toString() (padded with 0 to 20 length)
1. packages/slack-bolt-app/src/util/history.ts
- Added type definition and function to store session information
2. packages/slack-bolt-app/src/app.ts
- Modified to save session information only when a new thread is created (when thread_ts === undefined)
3. cdk/lib/constructs/storage.ts
- Added LocalSecondaryIndex (LSI1) to the DynamoDB table definition
- This …
=> Add session storage feature for DynamoDB

README.md, README_ja.md, cdk/lib/constructs/worker/index.ts, cdk/lib/constructs/worker/resources/image-component-template.yml, cdk/test/__snapshots__/cdk.test.ts.snap, packages/agent-core/src/lib/converse.ts, packages/slack-bolt-app/src/app.ts, packages/slack-bolt-app/src/async-handler.ts, packages/slack-bolt-app/src/util/worker-manager.ts, packages/worker/README.md, packages/worker/mcp.json, packages/worker/src/agent/mcp/index.ts
browser_install tool from playwright MCP fails to run after launched from a cached AMI.
The suggested workaround here https://github.com/microsoft/playwright-mcp/issues/218#issuecomment-2815992016 seems to fix the issue (adding `--browser=chromium`).
Also including some refactors.
=> fix playwright fails to run after started from a cached ami

packages/agent-core/src/lib/slack.ts, packages/agent-core/src/tools/report-progress/index.ts
- Removed the progress header ('progress' text) that appears in Slack message notifications
- Simplified the message display in Slack for better readability
- Modified related functions to no longer use the progress parameter
The progress header in Slack messages was unnecessary and removing it improves the message display.
Without this header, we add `@mention` to the final message in the agent's turn.
=> Remove progress header from Slack messages

packages/agent-core/src/lib/slack.ts
- Changed URL processing strategy to add spaces before URLs when needed
- Added function to automatically insert spaces before URLs that follow punctuation
- Applied this processing to both regular messages and file upload comments
- Changed message blocks from 'markdown' to 'section' with 'mrkdwn' type for better formatting
URLs in Slack messages are not being properly linked, especially when they appear directly after colons (e.g., '説明：https://example.com'). 
This change ensures that:
1. URLs are properly spaced from preceding punctuation
2. Slack's auto-linking can correctly identify URLs in the text
3. Links will be clickable even when they follow punctuation without spaces
The implementation detects URL protocol patterns ('http://' or 'https://') and adds a space before them if they …
=> Enhance URL detection and linking in Slack messages

packages/worker/src/agent/index.ts, packages/worker/src/agent/lib/knowledge.ts
This PR extends the knowledge file handling functionality to support multiple AI agent rule formats, inspired by the observation that there are now multiple competing standards for AI agent rules.
Reference: [Tweet by Aiden Bai](https://x.com/aidenybai/status/1923781810820968857) highlighting that 'there are now 9 competing standards for AI agent rules'
1. Added support for more knowledge file formats:
- Original formats: '.cursorrules'
- Additional formats: '.github/copilot-instructions.md', 'AGENT.md', 'AGENTS.md', '.cursor/rules/' directory
2. Added directory support:
- Paths ending with '/' are treated as directories
- All '.md' files in these directories are recursively searched
- Content from all found files is concatenated
3. Code improvements:
- Extracted knowledge file handling …
=> Add support for multiple AI agent rule formats

cdk/lib/constructs/worker/index.ts, cdk/test/__snapshots__/cdk.test.ts.snap, package-lock.json
closes #84
also updating some dependencies with npm audit fix.
We chose the first approach described in the doc. https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
=> fix playwright mcp fails to run

packages/agent-core/src/tools/command-execution/index.ts
This PR addresses [Issue #21](https://github.com/aws-samples/remote-swe-agents/issues/21) by adding support for daemon-like processes (e.g., `npm run dev` or `docker compose up`) in the executeCommand tool.
- Added a new property `longRunningProcess: boolean` to the existing `executeCommand` tool
- When `longRunningProcess: true`, the tool does not wait for the process to exit; instead, it leaves the process running in the background
- The tool waits for 10 seconds before returning control to allow for process initialization
- Any output generated during those 10 seconds is captured and returned to the agent
- If the process fails within the 10-second initialization period, an error is returned
- Built successfully with `npm run build`
- This enables the agent to start development servers …
=> feat: add longRunningProcess option to executeCommand tool

packages/slack-bolt-app/src/app.ts, packages/slack-bolt-app/src/util/history.ts, packages/webapp/src/app/(root)/actions.ts
closes #97.
1. Store initial message when creating a session item in  function
2. Updated  to return the initial message in the web app
3. Modified SessionItem type to include initialMessage field
- Verified that webapp can show initial message instead of last message in session list
=> Store and display initial message in sessions

packages/agent-core/src/lib/worker-manager.ts, packages/agent-core/src/schema/events.ts, packages/webapp/src/app/(root)/actions.ts, packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx, packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx, packages/webapp/src/app/sessions/new/actions.ts, packages/webapp/src/app/sessions/page.tsx, packages/webapp/src/app/sign-in/page.tsx, packages/worker/src/main.ts
This PR implements the EC2 instance status tracking and display feature as requested in issue #95.
- Add instanceStatus field to DynamoDB session records
- Add instanceStatusChanged event type to webapp event schema
- Update worker-manager to track and update instance status
- Add UI components to display instance status
- Update SessionPageClient to handle instanceStatus changes
- Send instanceStatus updates from EC2 instances via UserData script
Fixes #95
=> Add EC2 instance status tracking and display

packages/webapp/src/app/(root)/actions.ts, packages/webapp/src/app/sessions/page.tsx
Resolves #112
- Added display of session cost in USD to each session card in the sessions list
- Added DollarSign icon from lucide-react
- Cost values are formatted to show 2 decimal places with dollar sign prefix
This PR assumes that session.sessionCost field is available from DynamoDB as mentioned in the issue.
=> feat: show total cost of each session

packages/slack-bolt-app/src/app.ts
This PR fixes issue #120, which addresses a bug in the Slack message parsing logic where the app cannot correctly parse user messages if the mention is not at the beginning of the message.
1. Changed the parsing logic to use regex replacement instead of string slicing
2. Now correctly parses messages regardless of the position of the mention
The new implementation uses a regular expression to remove all mentions from the message text and properly handle whitespace.
Fixes #120
=> Fix: Slack message parsing when mention is not at beginning

packages/webapp/src/app/sessions/page.tsx
Changed the instance status indicator colors to be more intuitive:
1. Changed 'stopped' status indicator from blue to gray to better represent an inactive state
2. Changed 'starting' status indicator from yellow to blue as it's not a warning state and doesn't require caution
This makes the status indicators more intuitive and less confusing.
=> Change stopped instance indicator color from blue to gray

packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
Updated the SessionPageClient.tsx component to match the instance status indicator colors in the main sessions listing page:
- Changed 'starting' status indicator from yellow to blue
- Changed 'stopped' status indicator from blue to gray
This makes the status indicators consistent across all views in the application.
=> Update instance status indicator colors in SessionPageClient for consistency

packages/agent-core/src/tools/command-execution/index.ts, packages/agent-core/src/tools/command-execution/suggestion.ts, packages/webapp/src/actions/upload/action.ts, packages/webapp/src/app/sessions/[workerId]/component/MessageForm.tsx, packages/webapp/src/app/sessions/new/actions.ts, packages/webapp/src/app/sessions/new/page.tsx, packages/webapp/src/app/sessions/new/schemas.ts, packages/webapp/src/components/ImageUploader.tsx, packages/webapp/src/components/shared/ImageUploader.tsx
Added image upload functionality to new session form, similar to the existing MessageForm.tsx.
1. Created a shared image upload component (ImageUploader.tsx) to reduce code duplication
2. Modified MessageForm.tsx to use the shared component
3. Added image upload capability to the new session form
4. Updated related actions and schemas to handle image keys
Closes #133
=> (webapp): Allow to send images with new session form

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
This PR fixes an issue where line breaks in user messages were being converted to spaces in the UI.\n\n## Changes\n\n- Added custom paragraph component to ReactMarkdown that converts newlines to <br> tags\n- Implemented line break preservation by splitting text on newlines and inserting <br> elements\n\nThis ensures that when a user sends a message with multiple lines, the formatting is preserved in the UI.
=> Fix: Preserve line breaks in user messages

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
The showRawJson state in the ToolUseRenderer component of MessageList.tsx was being reset every time an event was received from the eventBus. This caused the JSON display to close whenever a new event occurred, even if the user had explicitly opened it.
1. Manage the showRawJson state at the component level using a Set called visibleRawJsonMessages in the MessageList component
2. Track which messages have their JSON display open using message IDs as keys
3. Add a toggleRawJsonVisibility function to manage state toggling
With these changes, the JSON display remains open even when new events occur, preserving the user's viewing preferences.
=> Fix showRawJson state reset issue in MessageList component

.github/workflows/deploy-prod.yml, README.md, cdk/bin/cdk.ts, cdk/lib/cdk-stack.ts, cdk/lib/constructs/worker/index.ts, cdk/test/__snapshots__/cdk.test.ts.snap, cdk/test/cdk.test.ts
This PR adds support for configuring additional AWS managed policies to be attached to the worker EC2 instance role.
- Added additionalAwsManagedPolicies parameter to WorkerProps interface 
- Modified worker role creation to include additional AWS managed policies specified via the new parameter
- Added environment variable parsing in CDK app to read policy names from WORKER_ADDITIONAL_POLICIES
- Updated README with documentation for the new feature
New environment variable WORKER_ADDITIONAL_POLICIES can be used to specify comma-separated list of AWS managed policy names to attach to worker instance. For example:
=> Add support for additional AWS managed policies to worker instance

README.md, README_ja.md, packages/slack-bolt-app/src/app.ts, resources/slack-app-manifest-relaxed.json
This PR addresses issue #127 by allowing users to send messages to agents in Slack without adding an @mention every time.
- Added detection of the bot's own ID using auth.test() API
- Created a common message processing function shared between event types
- Added message event handler to process messages:
- In DMs without mention
- In threads without mention
- Added detection to avoid duplicate processing when a message contains a mention
- Added unique idempotency keys to prevent duplicate processing
- Users can now continue a thread conversation without mentioning the bot
- In DMs, users can send messages without mentions
- In channels, new conversations still require an @mention to start
- Messages with @mentions are still processed by app_mention handler only
=> Allow sending messages without mentioning the slack app

packages/agent-core/src/schema/events.ts, packages/webapp/src/app/sessions/[workerId]/component/MessageForm.tsx, packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx, packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx, packages/webapp/src/app/sessions/[workerId]/page.tsx, packages/webapp/src/messages/en.json, packages/webapp/src/messages/ja.json, packages/worker/src/agent/index.ts
Fixes #144
1. Updated  to support showing toolResult JSON:
- Extended the state to track input and output JSON visibility separately
- Modified ToolUseRenderer to display both input and output JSON with separate buttons
2. Updated i18n files to support new labels:
- Added 'input' and 'output' labels to English and Japanese translations
3. Enhanced  to send toolResult output JSON in WebppEvent:
- Modified the schema to include optional output field
- Updated the event dispatch to include the tool result output
4. Updated SessionPageClient to process toolResult events:
- Implemented logic to update corresponding toolUse messages with output data
5. Updated page.tsx to handle toolResult data from DynamoDB:
- Added toolUseIds to Message type to help matching toolUse and toolResult
- …
=> Add tool result JSON display in webapp

packages/agent-core/src/lib/converse.ts, packages/agent-core/src/lib/cost.ts, packages/agent-core/src/lib/messages.ts, packages/worker/src/agent/index.ts
This PR addresses issue #148 by implementing middle out filtering during the agent's turn when the token count exceeds a threshold (95% of MAX_INPUT_TOKEN).
Currently, middle out filtering is only applied when starting an agent's turn, but it might lead to max token exceeded error when a turn continues for a long time. This change applies middle out even in the middle of a turn when token count exceeds the threshold.
- Added a token threshold check inside the while loop in agent/index.ts
- Applied middle out filtering when the token count exceeds 95% of MAX_INPUT_TOKEN
- Added more descriptive logging when middle out is applied during agent's turn
Fixes #148
=> worker: apply middle out when token count exceeds a threshold in agent's turn

packages/slack-bolt-app/src/app.ts
In the current implementation, message events with image attachments are not being processed because the code skips messages with a subtype (which include messages with file attachments).
This PR modifies the message event handler to:
1. Separate the bot message check from other conditions
2. Only skip messages that have no text AND no files
3. Allow messages with subtypes if they contain files
This ensures that the app properly processes messages with image attachments while still filtering out irrelevant messages.
=> Fix message event handler to process messages with image attachments

packages/agent-core/src/lib/sessions.ts
This PR modifies the getSessions function to use the LSI1 index for time-based sorting of sessions.\n\n- Added IndexName: 'LSI1' to the DynamoDB QueryCommand\n- The LSI1 index contains the createdAt timestamp in string format\n- ScanIndexForward: false ensures descending order (newest first)
=> Use LSI1 index to sort sessions by createdAt in descending order

AmazonQ.md
Add clear guidelines to the root AmazonQ.md file specifying that PRs should always be created against the upstream repository (aws-samples/remote-swe-agents) rather than personal forks.
=> Add PR guidelines to root AmazonQ.md

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
This PR fixes the behavior of the tool name button in MessageList.tsx when toggling JSON visibility. 
- Clicking the tool name button simply toggles both input and output JSON visibility states.
- If either input or output JSON is visible (true), clicking the tool name button will hide both (set both to false).
- If both are already hidden, the button does nothing.
This makes the UI behavior more intuitive when users want to collapse all JSON panels with a single click.
=> Fix tool JSON toggle button behavior

packages/webapp/src/app/sessions/[workerId]/component/MessageForm.tsx, packages/webapp/src/app/sessions/new/page.tsx, packages/webapp/src/messages/en.json, packages/webapp/src/messages/ja.json
This PR implements functionality to disable message sending while images are being uploaded.
- Disable textarea during image upload
- Disable submit button during image upload and change text to "Waiting for image upload..."
- Disable keyboard shortcut (Enter) for sending messages during image upload
- Disable textarea during image upload and update placeholder text to "Waiting for image upload..."
- Disable send button and change icon to loading indicator during image upload
- Disable keyboard shortcut (Enter) for sending messages during image upload
1. Access the sessions/new page and upload an image
2. Verify that the textarea and submit button are disabled during upload
3. Access the sessions/[workerId] page and upload an image
4. Verify that the textarea and send button are disabled …
=> Disable message sending during image upload

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
- モバイル表示時にローディングスピナーが左端に寄るようにCSSを修正
-  クラスを追加して明示的に左寄せ配置を指定
=> Fix: Align spinner to left edge on mobile view

package-lock.json, packages/agent-core/package.json, packages/agent-core/src/tools/github-pr-comments/index.ts
- This PR addresses issue #192
- Replaces GitHub CLI commands with Octokit API calls in the PR comments tools
- Adds @octokit/rest as a dependency
- Utilizes the existing GitHub token management functionality
- Added @octokit/rest as a dependency in agent-core
- Added getOctokitClient utility function to initialize authenticated Octokit instance
- Modified getPRCommentsHandler to use octokit.pulls.listReviewComments
- Modified replyPRCommentHandler to use octokit.pulls.createReplyForReviewComment
- Fixed test code to work with ESM
- Built successfully
- Type checking passed
Closes #192
=> Replace GitHub CLI with Octokit for PR comments API

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
This PR fixes a bug where syntax highlighting appears in light mode on mobile devices even when the system theme is set to dark mode.
- When the theme is set to "system" (following system preferences) and the device is using dark mode, syntax highlighting still shows in light mode on mobile devices
- Modified the useTheme hook to retrieve resolvedTheme in addition to theme
- Updated the syntax highlighter style selection logic to use only the resolvedTheme value to determine whether to apply dark theme styling
- Verified that syntax highlighting correctly displays in dark theme when the system is set to dark mode on mobile devices
=> Fix: Use resolvedTheme to apply correct syntax highlighting in dark mode on mobile

packages/webapp/src/app/api/auth/api-key.ts, packages/webapp/src/app/settings/api-keys/page.tsx
This PR updates the API authentication to use the x-api-key header instead of the Authorization: Bearer header. The middleware has been simplified to directly use the value from the x-api-key header, removing the need to parse the Bearer prefix. Documentation has also been updated to reflect this change.
=> Update API authentication to use x-api-key header

packages/agent-core/package.json, packages/agent-core/src/tools/editor/index.test.ts, packages/agent-core/src/tools/editor/index.ts, packages/agent-core/vitest.config.ts
This PR adds a new feature to the fileEditor tool that prevents overwriting existing files when oldString is empty. Previously, when a file existed and oldString was empty, it would proceed to later code, potentially causing unexpected behavior. Now it returns an appropriate error message.
- Added a check to prevent file modifications when oldString is empty but the file already exists
- Added a test case to verify this new behavior
- Verified that all tests pass including the new test case
=> Add check to prevent file overwrite when oldString is empty and file exists

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
Changed the alignment of executing text and loading icon from center-aligned (items-center) to bottom-aligned (items-end) in MessageList.tsx.
- Modified the flex container class from  to 
- This changes the vertical alignment of the text and icon to be aligned at the bottom
=> Change executing text alignment from center to bottom

packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx, packages/webapp/src/messages/en.json, packages/webapp/src/messages/ja.json
This PR adds a copy button to assistant messages in the MessageList component. The button only appears for messages with type 'message' and role 'assistant' as requested, allowing users to easily copy the assistant's responses to their clipboard.
- Added Copy icon button to assistant messages
- Button only appears for message type 'message' and role 'assistant' (not for toolUse messages)
- Added i18n support with English and Japanese translations
- Added clipboard copy functionality
=> Add copy button to assistant messages

packages/agent-core/src/tools/create-pr/index.ts
- Modified the createPullRequest tool to automatically run `git push -u origin <branchName>` before creating a pull request
- Removed the "IMPORTANT: Please make sure to push the current branch before using this tool" note from the tool description as it's no longer necessary
This change eliminates the need for the user to manually push their branch before creating a PR. The tool now automatically handles this step, making the PR creation process more seamless.
The added code gets the current branch name and pushes it to the remote repository before proceeding with PR creation. If the push operation fails, it throws an appropriate error message.
=> Add automatic git push before PR creation

packages/webapp/src/app/sessions/[workerId]/component/MessageItem.tsx, packages/webapp/src/app/sessions/[workerId]/component/UrlRenderer.tsx
This PR modifies the `MessageItem.tsx` component to disable Markdown rendering for user messages while still making URLs clickable.
- Created a new `UrlRenderer.tsx` component that detects URLs in text and makes them clickable
- Updated `MessageItem.tsx` to use the appropriate renderer based on message role:
- For user messages: Use the new `UrlRenderer` that only converts URLs to links
- For assistant messages: Continue using the existing `MarkdownRenderer`
- Verified that user messages no longer render Markdown formatting
- Verified that URLs in user messages still appear as clickable links
- Confirmed that assistant messages still render with full Markdown support
=> Disable markdown rendering for user messages except for URLs

packages/agent-core/src/tools/github-comments/index.ts
This PR adds workerId metadata to GitHub PR comments and issue comments, similar to how it's already implemented in the create-pr tool.
- Created a utility function `appendWorkerIdMetadata` that appends the workerId as an HTML comment to the message body
- Modified `replyPRCommentHandler` to use the utility function and add workerId metadata to PR comments
- Modified `addIssueCommentHandler` to use the utility function and add workerId metadata to issue comments
The changes follow the same pattern as in the create-pr tool implementation, ensuring consistency in the codebase.
The implementation follows the pattern established in `packages/agent-core/src/tools/create-pr/index.ts`, where comments include a hidden HTML comment with the workerId metadata.
=> Add workerId metadata to GitHub PR and issue comments

packages/webapp/src/app/layout.tsx
This PR adds a meta tag with `robots` content set to `noindex, nofollow` in the webapp's root layout file. This prevents search engines from indexing and following links on the web application.
- Added `<meta name="robots" content="noindex, nofollow" />` to the head section in `packages/webapp/src/app/layout.tsx`
- Verify that the meta tag is properly added to the HTML head when the application is rendered.
- This change will instruct search engines not to index the content of the web application.
=> Add noindex meta tag to prevent search engine indexing

packages/github-actions/src/handlers/pr-review.ts, packages/github-actions/src/index.ts
This PR adds support for handling `pull_request_review` events in the GitHub Actions component. When a pull request review is received, the handler will:
1. Search for session ID in the PR description
2. If a session ID is found, send the review message to the worker
3. Include relevant context about the review (reviewer, review state, etc.)
- Created a new handler in `packages/github-actions/src/handlers/pr-review.ts`
- Updated `index.ts` to listen and route `pull_request_review` events to this handler
- Implemented logic to extract the session ID from PR description
- Added message formatting similar to other event handlers
The implementation follows the same patterns as other event handlers in the repository, and should work as expected once deployed.
Closes #217
=> Add handler for pull_request_review events

packages/agent-core/src/tools/command-execution/index.ts
This PR adds a custom timeout option to the `executeCommand` tool, allowing the agent to change the default timeout value.
- Added a new `timeoutMs` parameter to the input schema allowing agents to set a custom timeout value
- Modified the `executeCommand` function to use this timeout parameter
- Updated the handler function to pass the custom timeout to the execution function
- Updated the tool description to provide clear guidance on when to use `timeoutMs` vs `longRunningProcess`:
- For daemon-like processes, use `longRunningProcess: true`
- For one-time tasks that take longer than 60 seconds to complete, use `timeoutMs` with a higher value
```javascript
// For a one-time task that may take up to 3 minutes
executeCommand({ 
command: "npm run build", 
timeoutMs: 180000 // 3 minutes in …
```
=> Add timeoutMs option to executeCommand tool

packages/webapp/src/app/sessions/new/NewSessionForm.tsx
This PR modifies the new session page to hide the "Initial Message" label on mobile devices while keeping it visible on larger screens (768px and above). This helps improve the mobile UI experience by reducing clutter on smaller screens.
- Added Tailwind CSS classes `hidden md:block` to the label element in `NewSessionForm.tsx`
- `hidden`: Hidden by default on mobile screens 
- `md:block`: Displayed as block element on medium screens (768px+)
=> Hide 'Initial Message' label on mobile screens

README.md, README_ja.md, cdk/bin/cdk.ts, cdk/lib/cdk-stack.ts, cdk/lib/constructs/worker/index.ts, cdk/test/__snapshots__/cdk.test.ts.snap
This PR adds support for setting the worker model override via an environment variable `WORKER_MODEL_OVERRIDE` when running CDK. This allows more flexibility in specifying the model to be used by the worker without having to modify the code directly.
- Added `workerModelOverride` property to `MainStackProps` interface in `cdk-stack.ts`
- Added `modelOverride` property to `WorkerProps` interface in `worker/index.ts`
- Added environment variable reading in `bin/cdk.ts` to set the model override from `WORKER_MODEL_OVERRIDE` environment variable
- Modified the worker service configuration to use the specified model override if provided
To specify a model override when deploying with CDK:
```
WORKER_MODEL_OVERRIDE=nova-pro npx cdk deploy
```
=> feat: add WORKER_MODEL_OVERRIDE environment variable support

cdk/lib/cdk-stack.ts, cdk/lib/constructs/slack-bolt/index.ts, cdk/lib/constructs/webapp.ts, cdk/test/__snapshots__/cdk.test.ts.snap, packages/agent-core/src/lib/aws/ssm.ts, packages/slack-bolt-app/src/handlers/message.ts
This PR adds a WebApp link to the initial Slack message when starting a new conversation with the agent. 
1. Modified `cdk/lib/constructs/slack-bolt/index.ts`:
- Added the SSM parameter for WebApp origin to Slack Lambda environment variables
- Added permission to read the parameter
2. Enhanced `packages/agent-core/src/lib/aws/ssm.ts`:
- Added a new function `getParameter` to retrieve SSM parameters
3. Updated `packages/slack-bolt-app/src/handlers/message.ts`:
- Added code to retrieve WebApp URL from SSM parameter
- Added WebApp session link to the initial message sent to user
- Improves user experience by providing easy access to the WebApp UI
- Creates better integration between the Slack and WebApp interfaces
- Users can easily switch between Slack and WebApp for the same session
=> Add WebApp link to initial Slack message

packages/agent-core/src/tools/create-pr/index.ts
This PR implements the functionality to set target branch when using the `createPullRequest` tool, as described in issue #264.
- Added `targetBranch` optional parameter to the `inputSchema` object
- Modified the PR creation command to include the `--base` option when `targetBranch` is provided
- The tool will continue to use the repository's default branch if no target branch is specified
Closes #264
---
**Open in Web UI**: https://d2c09i1k2ray87.cloudfront.net/sessions/1751595254698659
=> (agent-core): Set target branch when using createPullRequest tool

cdk/lib/constructs/worker/index.ts, cdk/test/__snapshots__/cdk.test.ts.snap
We now store the cursor position in file system so that it is not reset on every reboot.
=> fix fluent-bit log in cloudwatch is duplicated on instance reboot

packages/agent-core/src/lib/messages.ts, packages/worker/src/agent/index.ts
This PR adds the WebUI URL link to Slack messages when the agent finishes its turn. This makes it easier for users to access the WebUI session from anywhere in a long Slack thread without having to scroll back to the beginning.
- Added an optional `appendWebappUrl` parameter to `sendSystemMessage` function with default value of `false`
- When `appendWebappUrl` is `true`, the function appends a markdown link to the webapp session URL at the end of the Slack message: `([webapp](URL))`
- Modified the agent loop to use this parameter only at the end of the agent turn
- Modified `packages/agent-core/src/lib/messages.ts` to add the optional parameter and webapp URL handling
- Modified `packages/worker/src/agent/index.ts` to pass `true` for the parameter at the end of the agent loop
Fixes #270 …
=> Add WebUI URL to Slack messages at the end of agent loop

packages/worker/src/agent/index.ts
This PR adds an instruction to the system prompt that ensures Git branch names are unique by appending a timestamp `$(date +%s)` to the branch name.
- Added one line to the Git branch creation instructions in the system prompt
- The addition ensures branch name uniqueness by appending a Unix timestamp
- This prevents potential conflicts when multiple instances create branches with similar names
---
**Open in Web UI**: https://d2c09i1k2ray87.cloudfront.net/sessions/webapp-1751765376296
=> Add instruction to append timestamp to Git branch names

packages/worker/src/agent/index.ts
This PR modifies the behavior of the `ultrathink` keyword in the agent prompt. Previously, this keyword was instructed to be ignored semantically. With this change, when the keyword appears in user messages, the agent will:
- Use its thinking budget to maximum capacity
- Perform deep analysis before responding
This change will enable users to request more thorough analysis on complex topics when needed.
This change only affects the agent's prompt and behavior with a specific keyword and doesn't require additional unit tests.
---
**Open in Web UI**: https://d2c09i1k2ray87.cloudfront.net/sessions/webapp-1752725684662
=> Update ultrathink prompt directive

packages/agent-core/src/schema/events.ts, packages/webapp/src/app/sessions/[workerId]/component/MessageItem.tsx, packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx, packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx, packages/webapp/src/app/sessions/[workerId]/page.tsx, packages/webapp/src/messages/en.json, packages/webapp/src/messages/ja.json, packages/worker/src/agent/index.ts
This PR implements the display of reasoning/thinking content in the webapp as requested in issue #286.
- Added `reasoningText` field to `MessageView` type to store thinking content
- Updated `webappEventSchema` to include optional `reasoningText` property in message and toolUse events
- Modified `MessageItem.tsx` to display a "Show thinking" button when reasoning content is available
- Implemented a collapsible UI for displaying reasoning content
- Added translation strings for "Show thinking" and "Hide thinking" buttons in English and Japanese
- Updated worker to extract and pass reasoning content to the webapp in events
- Modified `page.tsx` to extract reasoning content from DynamoDB records
- Reasoning content is displayed in a collapsible section under the message
- Reasoning content …
=> Show extended thinking content in the webapp

packages/slack-bolt-app/src/handlers/message.ts, packages/slack-bolt-app/src/util/history.ts
Fix the below issues:
1. When the slack app is mentioned with an empty message, it throws Bedrock validation error.
2. When Slack workflow mentiones the app, the reply contains an invalid mention.
=> fix: slack empty mention and workflow replies

packages/agent-core/src/lib/converse.ts
This PR adds support for the Claude Opus 4.1 model (model ID: `us.anthropic.claude-opus-4-1-20250805-v1:0`).
- Added `'opus4.1'` to the model type enum in `modelTypeSchema`
- Added configuration for Opus 4.1 in `modelConfigs` based on existing Opus 4 settings
- Added case for Opus 4.1 in `chooseModelAndRegion` function with the specified model ID
No changes to default behavior. The model can now be selected as an available option when choosing models.
The configuration for Opus 4.1 is based on the existing Opus 4 configuration, as specified in the requirements.
---
**Open in Web UI**: https://d2c09i1k2ray87.cloudfront.net/sessions/webapp-1754626803463
=> Add support for Claude Opus 4.1 model

packages/webapp/src/app/sessions/new/NewSessionForm.tsx, packages/webapp/src/app/sessions/new/actions.ts
Previously, there was some lag between pushing `create new session` button and navigating to /sessions/:sessionId page.
This PR removes it and enhances the UX.
=> fix: navigate to new session page more smoothly

packages/agent-core/src/schema/preferences.ts
An error was thrown here
https://github.com/aws-samples/remote-swe-agents/blob/bf3aa3e800b8f610c3c92d84cec4100dcb9d95d3/packages/agent-core/src/lib/preferences.ts#L46-L53
because updatedAt is not set.
This PR makes updateAt an optional field.
=> fix: error when global preferences is not set

cdk/lib/constructs/worker/index.ts, cdk/lib/constructs/worker/resources/image-component-template.yml, cdk/test/__snapshots__/cdk.test.ts.snap
The validation step was not working properly; it unexpectedly succeed even when some of the commands are missing. Thi s PR adds `|| exit 1` for every command to exit with error when a command failed.
=> fix: ec2 builder validation step was not working
