aws-samples/remote-swe-agents

- README.md
README.mdファイル内の英文を校正し、より自然な英語表現に改善しました。内容そのものは変更せず、言い回しの修正に注力しました。
主な修正点:
- 文法的な誤り（an fully → a fully）の修正
- 表現の改善（"you are now free from your laptops" → "freeing you from being tied to your laptop"）
- 一貫性のある表現にするための調整
- 読みやすさの向上のためのフレーズの書き換え
より正確で自然な英語表現を用いることで、ドキュメントの品質を向上させ、読者の理解を促進する。
> Improve English phrasing in README.md

- README.md
- slack-bolt-app/src/app.ts
- slack-bolt-app/src/util/cost.ts
- worker/package-lock.json
- worker/src/agent/common/bedrock.ts
- worker/src/agent/common/messages.ts
- worker/src/agent/index.ts
- worker/src/agent/tools/browser/index.ts
- worker/src/local.ts
n/a
Support prompt cache for Sonnet3.7 for token efficiency.
https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-caching.html
> enable prompt caching

- README.md
This PR improves the README documentation by enhancing the installation instructions to make them more user-friendly.
> Enhance installation instructions

- worker/src/agent/index.ts
This PR improves the system prompt in several ways:
1. **Git Branch Usage**: Added instructions for agents to always work in feature branches rather than directly on main/master
- Creates proper isolation of changes
- Follows Git best practices
- Makes PRs and code review clearer
2. **Language Rules for Reasoning**: Added directive that internal reasoning (not visible to users) should always be in English
- Ensures consistent internal processing
- Maintains multilingual user interface while standardizing behind-the-scenes work
3. **Interface References**: Updated interface references from command-line to Slack
- Removed CLI-specific formatting instructions
- Added appropriate Slack context
- Modified display guidelines to match Slack interface
These changes will improve agent behavior …
> Improve system prompt with branch usage, language rules, and interface clarity

- worker/src/agent/index.ts
This PR further enhances the planning guidance for agents by adding explicit instructions to identify and clarify ambiguous requirements. The changes:
1. **Expanded scope**: Changed from "For complex tasks" to "For ALL tasks beyond trivial ones" to ensure consistent planning behavior
2. **Added requirement clarification**: Explicitly instructs agents to identify unclear or ambiguous aspects of requirements and ask questions before proceeding
3. **Added assumption documentation**: Requires agents to list any assumptions they're making about requirements, which allows users to correct misunderstandings early
4. **Enhanced implementation approach**: Changed to request step-by-step breakdown, making plans more detailed and easier to review
5. **Strengthened confirmation requirement**: Added …
> Enhance planning guidance with clarification instructions

- cdk/lib/constructs/worker/index.ts
- cdk/test/__snapshots__/cdk.test.ts.snap
- worker/src/agent/index.ts
> use Ubuntu instead of AL2023

- README.md
- cdk/lib/constructs/worker/index.ts
- cdk/test/__snapshots__/cdk.test.ts.snap
- worker/src/agent/common/bedrock.ts
- worker/src/agent/index.ts
- worker/src/agent/tools/browser/index.ts
> Allow to use Nova Pro model (experimental)

- .github/workflows/build.yml
- docker/slack-bolt-app.Dockerfile
- packages/slack-bolt-app/package.json
- packages/slack-bolt-app/src/local.ts
Root cause: The native binaries required by `sharp` package were not installed. We now install them in the Dockerfile and make sure the image boots successfully in CI.
> fix slack bolt boot failure

- packages/agent-core/src/private/common/lib.ts
- packages/worker/src/agent/index.ts
> add prompt not to use web browser for GitHub URLs

- cdk/lib/constructs/worker/image-builder.ts
- cdk/lib/constructs/worker/index.ts
- cdk/package-lock.json
- cdk/test/__snapshots__/cdk.test.ts.snap
It turned out the agent cannot use docker at all. We now follow the official installation guide.
> fix docker installation

- packages/agent-core/src/lib/converse.ts
- packages/agent-core/src/lib/index.ts
- packages/worker/src/agent/index.ts
- packages/worker/src/common/cancellation-token.ts
- packages/worker/src/local.ts
- packages/worker/src/main.ts
> Allow cancelling ongoing converse session

- packages/agent-core/src/lib/converse.ts
closes #76 
Changed the rules for the Bedrock account LB feature. Switch when throttling occurs.
> feat: change rule of account lb

- README.md
- packages/agent-core/src/lib/converse.ts
- packages/agent-core/src/tools/command-execution/index.ts
- packages/worker/src/agent/index.ts
closes #90 
Currently sonnet 4 is throttled severely so we keep the default model sonnet 3.7.
> support Claude 4

- .github/workflows/build.yml
- cdk/lib/constructs/cf-lambda-furl-service/lambda/sign-payload.ts
- cdk/lib/constructs/cf-lambda-furl-service/service.ts
- cdk/package-lock.json
- cdk/package.json
- cdk/test/__snapshots__/cdk.test.ts.snap
- cdk/test/cdk.test.ts
- packages/agent-core/src/env.ts
- packages/agent-core/src/lib/events.ts
- packages/agent-core/src/tools/report-progress/index.ts
- packages/webapp/package.json
- packages/webapp/src/app/(root)/actions.ts
- packages/webapp/src/app/(root)/page.tsx
- packages/webapp/src/app/layout.tsx
- packages/webapp/src/app/sessions/new/page.tsx
- packages/webapp/src/app/sessions/page.tsx
- packages/webapp/src/app/sign-in/page.tsx
- packages/webapp/src/components/ui/button.tsx
- packages/webapp/src/hooks/use-event-bus.ts
- packages/webapp/src/lib/jobs.ts
… signPayloadHandler, fix webapp path, format agent-core files
> Fix CI issues for PR #93

- docker/webapp.Dockerfile
- package-lock.json
- package.json
- patches/@aws-amplify+adapter-nextjs+1.6.2.patch
Due to CloudFront issue, it takes a minute to navigate to cognito sign-in page. The workaround is to add some body to the redirect response. 
We cannot directly modify the redirect response because it is encapsulated in the amplify library. That's why we use patch-package instead.
> fix: navigating to cognito signin page takes a minute

- cdk/lib/cdk-stack.ts
- cdk/lib/constructs/slack-bolt/index.ts
- cdk/lib/constructs/webapp.ts
- cdk/test/__snapshots__/cdk.test.ts.snap
iam permission was not properly configured.
> fix starting an agent fails from webapp

- .prettierignore
- cdk/jest.config.js
- package.json
- packages/webapp/src/app/sign-in/page.tsx
0559c7d9f0b3815b1c4d25ed6bcf8c56aa15f4e8 コミットをrevertしました。フォーマットはwebappサブディレクトリのみの範囲で確認し、不要なフォーマット変更は含めていません。
> Revert "prevent cors error on sign-in"

- packages/agent-core/src/tools/command-execution/index.ts
- packages/agent-core/src/tools/command-execution/suggestion.ts
The agent sometimes fails to follow some expected behaviors, e.g. checking CI status after git push, or reporting PR URL after creating one. This PR tries to fix the issue by adding suggestion after command excecution.
Please hide whitespace changes when check the diff.
> make suggestion after executing some specific commands

- package-lock.json
- packages/webapp/next.config.ts
- packages/webapp/package.json
- packages/webapp/src/app/sessions/[workerId]/component/MessageForm.tsx
- packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
- packages/webapp/src/app/sessions/new/page.tsx
- packages/webapp/src/app/sessions/page.tsx
- packages/webapp/src/messages/en.json
- packages/webapp/src/messages/ja.json
This PR completes the i18n implementation for all TSX files in the webapp:\n\n- Added missing translations to the en.json and ja.json files\n- Updated all components to use translations instead of hardcoded strings\n- Components modified:\n  - MessageList.tsx\n  - MessageForm.tsx\n  - SessionPageClient.tsx\n  - sessions/page.tsx\n  - sessions/new/page.tsx
> Complete i18n implementation for webapp

- packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
- packages/webapp/src/hooks/use-scroll-position.ts
- packages/webapp/src/messages/en.json
- packages/webapp/src/messages/ja.json
- Added auto-scroll to bottom when opening the page or when new messages arrive
- Made header sticky to access menu anytime
- Added buttons to scroll to top or bottom of the page
- prevent cognito-token refetch every time a new message is added
This PR introduces UI improvements to enhance user experience on session page.
> (webapp): improve usability of the session page

- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
This PR implements the following changes:\n\n1. Consolidated the header into a single row\n2. Removed the "Chat with AI Agent" label\n3. Maintained instance status display\n4. Added a "New Session" button on the right side
> Improve header layout

- packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
This PR changes the color of the output text in the sessions/[workerId] page to green when the output section is expanded.
> Change output text color to green

- packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
- packages/webapp/src/components/Header.tsx
- packages/webapp/src/messages/ja.json
> Improve messagePanel design

- packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
This PR addresses the issue where long lines in Markdown content were not properly wrapped in the webapp MessageList component.
- Added , , and  Tailwind classes to the Markdown renderer container to ensure proper text wrapping for long lines.
- Tested with long text lines, including URLs and code snippets, to ensure proper wrapping behavior.
> Fix Markdown text wrapping in webapp MessageList component

- packages/webapp/src/app/sessions/[workerId]/actions.ts
- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
- packages/webapp/src/app/sessions/[workerId]/component/TodoList.tsx
- packages/webapp/src/app/sessions/[workerId]/schemas.ts
Closes #163
This PR implements the feature to refetch todoList when todoInit or todoUpdate tool use is received from the event bus.
1. Added server action  to get the latest todo list
2. Added logic to refetch todoList when todoInit or todoUpdate tool is used in both toolUse and toolResult events
3. Refactored the code to improve maintainability and performance by creating a reusable refetch function
Tested manually - todoList is refreshed correctly when todoInit or todoUpdate tools are used.
> (webapp): refetch todoList when todoInit or todoUpdate task use is received from event bus

- packages/webapp/src/app/layout.tsx
- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
- packages/webapp/src/messages/en.json
- packages/webapp/src/messages/ja.json
> Move Complete button

- packages/webapp/src/app/sessions/[workerId]/component/MessageList.tsx
Add break-all CSS style to inline code blocks in MessageList component to ensure proper text wrapping for long inline code blocks.
- Added break-all style to inline code blocks in MessageList.tsx
> Fix inline code block wrapping with break-all style

- packages/agent-core/src/tools/command-execution/index.ts
- packages/agent-core/src/tools/command-execution/suggestion.ts
- packages/agent-core/src/tools/create-pr/index.ts
- packages/agent-core/src/tools/index.ts
- packages/webapp/src/app/sessions/[workerId]/component/SessionPageClient.tsx
- packages/worker/src/agent/index.ts
> Create pr tool

- packages/webapp/src/app/api/sessions/[sessionId]/route.ts
- packages/webapp/src/app/settings/api-keys/page.tsx
- packages/webapp/src/messages/en.json
- packages/webapp/src/messages/ja.json
> History api

- packages/webapp/src/app/(root)/page.tsx
- Added `items-center` class to the button container div to ensure buttons are centered on mobile view when in column layout
- Removed `hidden sm:inline` class from the "New Session" button text to ensure the text is always visible on all screen sizes, including mobile
Before changes:
- Buttons on mobile were not centered
- "New Session" button text was hidden on mobile, showing only the Plus icon
After changes:
- Buttons on mobile are properly centered
- "New Session" button shows text on all screen sizes including mobile
> Improve mobile UI of root page

- .github/workflows/deploy-prod.yml
- cdk/lib/constructs/lambda-warmer/index.ts
- cdk/lib/constructs/lambda-warmer/lambda/handler.ts
- cdk/lib/constructs/lambda-warmer/lambda/type.ts
- cdk/lib/constructs/webapp.ts
- packages/webapp/src/app/api/health/warm/route.ts
to reduce webapp cold start. for temporary use only.
> add lambda warmer

- packages/agent-core/src/lib/sessions.ts
- packages/agent-core/src/schema/session.ts
- packages/slack-bolt-app/src/handlers/message.ts
- packages/slack-bolt-app/src/util/session.ts
- packages/webapp/src/app/api/sessions/route.ts
- packages/webapp/src/app/sessions/(root)/components/SessionsList.tsx
- packages/webapp/src/app/sessions/(root)/page.tsx
- packages/webapp/src/app/sessions/new/actions.ts
- packages/webapp/src/messages/en.json
- packages/webapp/src/messages/ja.json
Sessions initiated by other cognito users or other method (rest or slack) is now emphasized with the people icon.
This should allow easily distinguish which session is mine when used by multiple users.
> Emphasize my session

- packages/agent-core/src/lib/sessions.ts
- packages/agent-core/src/schema/session.ts
- packages/webapp/src/app/sessions/(root)/actions.ts
- packages/webapp/src/app/sessions/(root)/components/SessionsList.tsx
> allow hiding sessions when pressing shift key

- cdk/lib/cdk-stack.ts
- cdk/lib/constructs/slack-bolt/index.ts
- cdk/lib/constructs/webapp.ts
- cdk/lib/constructs/worker/index.ts
- cdk/test/__snapshots__/cdk.test.ts.snap
- packages/agent-core/src/lib/index.ts
- packages/agent-core/src/lib/webapp-origin.ts
- packages/agent-core/src/tools/create-pr/index.ts
- packages/slack-bolt-app/src/handlers/message.ts
> show webapp url in PR body

- .github/workflows/build.yml
This PR optimizes the CI/CD pipeline by only building and testing packages that have been modified in the PR. This significantly reduces CI execution time.
1. **Added Changed Files Detection Job**
- Uses the dorny/paths-filter@v3 action to detect modified file paths
- Set up change filters for each package (cdk, agent-core, slack-bolt-app, etc.)
- Configured filters considering dependencies (when agent-core changes, dependent packages are also targeted)
2. **Conditional Job Execution**
- Added conditions to each build job to run only when corresponding packages are changed
- All jobs still run on main branch pushes or manual workflow executions
3. **Concurrency Settings**
- Added concurrency settings to prevent multiple PR builds from running in parallel on the same branch
- Automatically …
> Optimize CI pipeline by only building changed packages

- packages/worker/src/agent/index.ts
This PR adds an important security instruction to the agent system prompt to explicitly prevent the agent from revealing environment variables, credentials, tokens, API keys, or other system configuration details under any circumstances.
- Added a clear security directive in the agent's system prompt to refuse requests for sensitive information
- Included guidance to suggest secure alternatives when users request sensitive data
- Specifically mentioned protection against direct, obfuscated, and encoded requests for sensitive data
This change addresses a security vulnerability where users could potentially trick the agent into revealing sensitive environment variables and credentials through direct or obfuscated requests. By adding an explicit security instruction to the system prompt, we …
> Add security instruction to prevent revealing sensitive information

- packages/webapp/src/app/settings/prompt/components/PreferenceSection.tsx
- packages/webapp/src/app/settings/prompt/components/PromptForm.tsx
- packages/webapp/src/app/settings/prompt/page.tsx
- packages/webapp/src/components/Header.tsx
- packages/webapp/src/messages/en.json
- packages/webapp/src/messages/ja.json
We'll add other global settings in this page.
> feat: rename prompt setting page to preference page

- packages/webapp/src/app/sessions/[workerId]/component/MessageForm.tsx
- packages/webapp/src/app/sessions/[workerId]/schemas.ts
Sometimes the input becomes a bit laggy. Before confirming the fix, the problem went away due to other factors (maybe my laptop was just in high load) so I'm not sure if this PR is the complete fix. At least I improved some code so merging now.
> fix: message form input is laggy

- .github/workflows/build.yml
- package-lock.json
This PR addresses security vulnerabilities identified by `npm audit`.
- **axios DoS vulnerability** (GHSA-4hjh-wcwx-xvwj)
- Fixed by updating to axios >=1.12.0
- Resolves DoS attack vulnerability through lack of data size check
- **Vite file serving vulnerabilities**
- GHSA-g4jq-h2w9-997c: Middleware may serve files with same name prefix
- GHSA-jqfw-vq24-v9c3: `server.fs` settings not applied to HTML files
- Fixed by updating Vite to secure version
The following vulnerabilities are **not addressed** in this PR:
- **Issue**: GHSA-x7hr-w5r2-h6wg - PrismJS DOM Clobbering vulnerability  
- **Affected**: `react-syntax-highlighter` package dependencies
- **Status**: **Requires upstream fix** - dependency chain needs react-syntax-highlighter major version update
- **Impact**: Breaking changes …
> Fix npm security vulnerabilities
